version: "2"

networks:
  raptor_stream:
    driver: bridge

services:

  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_DB=streams
      - INFLUXDB_USER=raptor
      - INFLUXDB_USER_PASSWORD=raptor
    networks:
      - raptor_stream
